export const types = {
    SAVE_LAST_HISTORY : 'SAVE_LAST_HISTORY',
    SAVE_MISSING_DATES : 'SAVE_MISSING_DATES',
    SAVE_CONTEXT_DATE: 'SAVE_CONTEXT_DATE',
    UDPATE_SEARCH_PARAMS:'UDPATE_SEARCH_PARAMS',
    SAVE_SAVED_SEARCHES : 'SAVE_SAVED_SEARCHES',
    ADD_SAVED_SEARCH : 'ADD_SAVED_SEARCH',
    DELETE_SAVED_SEARCH : 'DELETE_SAVED_SEARCH',

}